### ISSUE TITLE
64-bit Meshing

### ISSUE THREAD

**Issue by william-silversmith** [seung-lab/igneous#1]
On Ran's agglomeration test:

`raised value too large to convert to unsigned int Traceback (most recent call last): File "/igneous/igneous/task_execution.py", line 60, in execute task.execute() File "/igneous/igneous/tasks.py", line 219, in execute self._compute_meshes() File "/igneous/igneous/tasks.py", line 224, in _compute_meshes self._mesher.mesh(data.flatten(), *data.shape[:3]) File "_mesher.pyx", line 34, in _mesher.Mesher.mesh File "stringsource", line 48, in vector.from_py.__pyx_convert_vector_from_py_unsigned_int OverflowError: value too large to convert to unsigned int MeshTask(shape=[512, 512, 512],offset=[2635, 2000, 522],layer_path='gs://neuroglancer/ranl/flyem_agglomeration_test',mip=3,simplification_factor=100,max_simplification_error=40) on host igneous-1996647607-q94q2`

Necessary for Phase II.

**Comment by william-silversmith** [comment]
The meshing seems to work if the data are within range of a uint32
