### ISSUE TITLE
ImportError: cannot import name 'getprecision' from 'cloudvolume.lib' error

### ISSUE THREAD

**Issue by manoaman** [seung-lab/igneous#110]
Hi,

I am experiencing the following missing module error while trying to run igneous.  I think my cloud-volume package is up to date but not sure what I am missing here.  Could you please advise what needs to be updated?

```
Traceback (most recent call last):
  File "igneous_.py", line 5, in <module>
    import igneous.task_creation as tc
  File "{...my path...}/git/igneous/igneous/__init__.py", line 3, in <module>
    from .tasks import *
  File "{...my path...}/git/igneous/igneous/tasks/__init__.py", line 3, in <module>
    from .image import (
  File "{...my path...}/git/igneous/igneous/tasks/image.py", line 25, in <module>
    from igneous import downsample_scales
  File "{...my path...}/git/igneous/igneous/downsample_scales.py", line 19, in <module>
    from cloudvolume.lib import min2, getprecision
ImportError: cannot import name 'getprecision' from 'cloudvolume.lib' (/{...my path...}}/lib/python3.7/site-packages/cloudvolume/lib.py)
```

This is the code I'm trying to run.
```
from cloudvolume import Vec
from taskqueue import LocalTaskQueue
import igneous.task_creation as tc
import sys

src_layer_path = '....'
dest_layer_path = '....'

print(src_layer_path)
print(dest_layer_path)

with LocalTaskQueue(parallel=8) as tq:
  tasks = tc.create_transfer_tasks(
    src_layer_path, dest_layer_path, 
    chunk_size=(64,64,64), shape=Vec(512,512,512),
    fill_missing=False, translate=(0,0,0), 
    bounds=None, mip=0, preserve_chunk_size=True,
    encoding=None, skip_downsamples=False,
    delete_black_uploads=False
  )

  tq.insert_all(tasks)

print("Done!")
```

Thank you,
m

**Comment by william-silversmith** [comment]
Hi m,

Can you use pip freeze to report the version of CloudVolume you have? getprecision is a newer function so an outdated version won't have it.

**Comment by manoaman** [comment]
Hi Will,

I'm using 3.8.0 in my conda environment.

```
pip freeze cloud-volume | grep cloud-volume
cloud-volume==3.8.0
```
-m

**Comment by manoaman** [comment]
I'd have to wait until igneous completes but It seems to be running okay from the upgrade.  Thank you!

```
pip install cloud-volume --upgrade
pip freeze | grep cloud-volume
cloud-volume==5.3.2
```

**Comment by william-silversmith** [comment]
I'm glad that worked! Let me know when the run completes and I can close this issue.

**Comment by manoaman** [comment]
Hi Will, yes, igneous completed okay and please go ahead and close this issue.  Thanks!
