### ISSUE TITLE
raised 'NotImplementedError' object has no attribute 'lease'

### ISSUE THREAD

**Issue by jingpengw** [seung-lab/igneous#28]
I am trying to run GPU inference for mitochondria map, but get some errors, any idea? @william-silversmith 
I have tried to upgrade taskqueue, but still have this problem. I am using the `chunkflow` branch though. do I need to merge the master?

```
(jwu) ~/workspace/igneous/igneous$ export SQS_URL=https://sqs.us-east-1.amazonaws.com/098703261575/jwu-igneous; export LEASE_SECONDS=3600; python task_execution.py --qurl https://sqs.us-east-1.amazonaws.com/098703261575/jwu-igneous --loop
Pulling from pull-queue://https://sqs.us-east-1.amazonaws.com/098703261575/jwu-igneous
raised 'NotImplementedError' object has no attribute 'lease'
 Traceback (most recent call last):
  File "task_execution.py", line 71, in execute
    task = tq.lease(tag=tag, seconds=int(LEASE_SECONDS))
  File "/usr/people/jingpeng/workspace/igneous/jwu/lib/python3.5/site-packages/taskqueue/taskqueue.py", line 152, in lease                                                         
    tasks = self._api.lease(
AttributeError: 'NotImplementedError' object has no attribute 'lease'

 undefined task
 on host seungworkstation20
Traceback (most recent call last):
  File "task_execution.py", line 94, in <module>
    command()
  File "/usr/people/jingpeng/workspace/igneous/jwu/lib/python3.5/site-packages/click/core.py", line 722, in __call__                                                               
    return self.main(*args, **kwargs)
  File "/usr/people/jingpeng/workspace/igneous/jwu/lib/python3.5/site-packages/click/core.py", line 697, in main                                                                   
    rv = self.invoke(ctx)
  File "/usr/people/jingpeng/workspace/igneous/jwu/lib/python3.5/site-packages/click/core.py", line 895, in invoke                                                                 
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/people/jingpeng/workspace/igneous/jwu/lib/python3.5/site-packages/click/core.py", line 535, in invoke                                                                 
    return callback(*args, **kwargs)
  File "task_execution.py", line 34, in command
    execute(tag, queue, server, qurl, loop)
  File "task_execution.py", line 71, in execute
    task = tq.lease(tag=tag, seconds=int(LEASE_SECONDS))
  File "/usr/people/jingpeng/workspace/igneous/jwu/lib/python3.5/site-packages/taskqueue/taskqueue.py", line 152, in lease                                                         
    tasks = self._api.lease(
AttributeError: 'NotImplementedError' object has no attribute 'lease'
```

**Comment by jingpengw** [comment]
this is because I did not specify the --server option.
The error message did not give correct hint, this option should be set as required though.
