### ISSUE TITLE
error from consensus building task

### ISSUE THREAD

**Issue by jingpengw** [seung-lab/igneous#31]
I am running our consensus building routing.

This is the command I am using:
```
sudo docker run -v /secrets:/secrets seunglab/
igneous:master bash -c ' export PIPELINE_USER_QUEUE=zfish;  export QUEUE_TYPE=sqs; export SQS_UR
L=https://sqs.us-east-1.amazonaws.com/098703261575/zfish;  export LEASE_SECONDS=600; alias pytho
n=python3; export LC_ALL=C.UTF-8; export LANG=C.UTF-8; python /igneous/igneous/task_execution.py
 '
``` 
it used to work well, but I am getting some error now.
```
Pulling from sqs://https://sqs.us-east-1.amazonaws.com/098703261575/zfish
HyperSquareConsensusTask(src_path='gs://neuroglancer/zfish_v1/segmentation2',dest_path='gs://neu
roglancer/zfish_v1/consensus-20181125',ew_volume_id=28652,consensus_map_path='gs://neuroglancer/
zfish_v1/consensus-20181125/zfish_consensus.all.json',shape=[896, 896, 112],offset=[72960, 29952
, 16848])
Deprecation Warning: /root/.cloudvolume/secrets/google-secret.json is now preferred to /secrets/
google-secret.json.
raised a bytes-like object is required, not 'NoneType'
 Traceback (most recent call last):
  File "/igneous/igneous/task_execution.py", line 74, in execute
    task.execute()
  File "/igneous/igneous/tasks/tasks.py", line 646, in execute
    consensus = cache(self, self.consensus_map_path).decode('utf8')
  File "/igneous/igneous/tasks/tasks.py", line 92, in cache
    f.write(filestr)
TypeError: a bytes-like object is required, not 'NoneType'
 HyperSquareConsensusTask(src_path='gs://neuroglancer/zfish_v1/segmentation2',dest_path='gs://ne
uroglancer/zfish_v1/consensus-20181125',ew_volume_id=28652,consensus_map_path='gs://neuroglancer
/zfish_v1/consensus-20181125/zfish_consensus.all.json',shape=[896, 896, 112],offset=[72960, 2995
2, 16848])
 on host 98906f76805c
Traceback (most recent call last):
  File "/igneous/igneous/task_execution.py", line 94, in <module>
    command()
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/igneous/igneous/task_execution.py", line 34, in command
    execute(tag, queue, server, qurl, loop)
  File "/igneous/igneous/task_execution.py", line 74, in execute
    task.execute()
  File "/igneous/igneous/tasks/tasks.py", line 646, in execute
    consensus = cache(self, self.consensus_map_path).decode('utf8')
  File "/igneous/igneous/tasks/tasks.py", line 92, in cache
    f.write(filestr)
TypeError: a bytes-like object is required, not 'NoneType'
```

**Comment by jingpengw** [comment]
according to the error message, it seems a string coding problem.

**Comment by jingpengw** [comment]
my parameters were not set correctly.
