### ISSUE TITLE
documentation for docker usage?

### ISSUE THREAD

**Issue by jingpengw** [seung-lab/igneous#8]
Hi, I am trying to use docker, but get some errors. I am probably not using it correctly, could you give me a hint?

```
~/workspace/zfish_analysis: docker run -it -v /secrets:/secrets -v /import:/import -e "LEASE_SECONDS=3000" seunglab/igneous:master
Deprecation Warning: /root/.cloudvolume/secrets/google-secret.json is now preferred to /secrets/google-secret.json.
Deprecation Warning: /root/.cloudvolume/secrets/aws-secret.json is now preferred to /secrets/aws-secret.json.
Deprecation Warning: /root/.cloudvolume/secrets/boss-secret.json is now preferred to /secrets/boss-secret.json.
Pulling from pull-queue://pull-queue
raised name 'leaseSecs' is not defined
 Traceback (most recent call last):
  File "/igneous/igneous/task_execution.py", line 70, in execute
    task = tq.lease(tag=tag, seconds=int(LEASE_SECONDS))
  File "/usr/local/lib/python3.4/site-packages/taskqueue/taskqueue.py", line 155, in lease
    tag=tag,
  File "/usr/local/lib/python3.4/site-packages/taskqueue/google_queue_api.py", line 110, in lease
    'leaseSecs': leaseSecs,
NameError: name 'leaseSecs' is not defined

 undefined task
 on host 4d57a4214084
Traceback (most recent call last):
  File "/igneous/igneous/task_execution.py", line 89, in <module>
    command()
  File "/usr/local/lib/python3.4/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.4/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.4/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/igneous/igneous/task_execution.py", line 33, in command
    execute(tag, queue, server, qurl)
  File "/igneous/igneous/task_execution.py", line 70, in execute
    task = tq.lease(tag=tag, seconds=int(LEASE_SECONDS))
  File "/usr/local/lib/python3.4/site-packages/taskqueue/taskqueue.py", line 155, in lease
    tag=tag,
  File "/usr/local/lib/python3.4/site-packages/taskqueue/google_queue_api.py", line 110, in lease
    'leaseSecs': leaseSecs, 
NameError: name 'leaseSecs' is not defined
```

**Comment by william-silversmith** [comment]
That happens if you use the Google CloudTasks which is broken. Try using
the AWS SQS service.

**Comment by william-silversmith** [comment]
I updated the example deployment.yml file about a month ago.
